name: Merge

on:
  workflow_dispatch:
  push:
    branches:
      - main

# Reference: https://docs.github.com/en/actions/security-guides/automatic-token-authentication
permissions:
  # Need `contents: read` to checkout the repository.
  # Need `contents: write` to update the step metadata.
  contents: write


    # We'll run Ubuntu for performance instead of Mac or Windows.
    runs-on: ubuntu-latest

